sequenceDiagram
    participant Node
    participant TLS as "TLS Distributed Plugin"
    participant Server

    Node->>TLS: pullUpdates()
    TLS->>Server: POST read endpoint
    Server->>TLS: JSON queries
    TLS->>Node: return JSON
    Node->>TLS: writeResults(JSON)
    TLS->>Server: POST write endpoint
