classDiagram
    class callback_data {
        +int echoOn
        +int mode
        +int showHeader
        +char separator[20]
        +char nullvalue[20]
        +FILE* out
        +sqlite3_stmt* pStmt
        +prettyprint_data* prettyPrint
    }
