flowchart TD
    QueryLogItem["QueryLogItem"]
    QueryLogItem --> IsSnapshot["isSnapshot"]
    QueryLogItem --> DiffRes["DiffResults"]
    QueryLogItem --> Snapshot["snapshot_results"]
    QueryLogItem --> Name["name"]
    QueryLogItem --> Identifier["identifier"]
    QueryLogItem --> Time["time"]
    QueryLogItem --> Epoch["epoch"]
    QueryLogItem --> Counter["counter"]
    QueryLogItem --> CalendarTime["calendar_time"]
    QueryLogItem --> Decorations["decorations"]
