name: OSQuery Build and Push Latest

permissions:
  contents: write
  packages: write
  actions: write
  pull-requests: write
  attestations: write
  id-token: write

on:
  push:
    branches: [master,feature/sanitize-logs]
    paths-ignore:
      - "**/*.md"
      - '.github/**'
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v1.2.3)"
        required: true
        type: string

env:
  REGISTRY: "ghcr.io"
  ORGANISATION: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  CMAKE_OSX_DEPLOYMENT_TARGET: "15.0"
  CMAKE_BUILD_TYPE: Release
  BINARY_NAME: osqueryd

# =============================================================================
# JOBS
# =============================================================================

jobs:
  build_macos:
    name: "Build C Client for (${{ matrix.os }} ${{ matrix.os_arch }})"
    runs-on: ${{ matrix.os }}
    if: |
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "macOS x86-64"
            os: macos-13
            os_arch: x86-64
            cmake_arch: x86_64
            artifact_name: osquery-macos-x64
          - name: "macOS ARM64"
            os: macos-latest
            os_arch: arm64
            cmake_arch: arm64
            artifact_name: osquery-macos-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Xcode Command Line Tools
        shell: bash
        run: |
          # Install Xcode if not already installed
          if ! xcode-select -p >/dev/null 2>&1; then
            echo "Installing Xcode Command Line Tools..."
            xcode-select --install
            # Wait for installation to complete
            while ! xcode-select -p >/dev/null 2>&1; do
              echo "Waiting for Xcode Command Line Tools installation..."
              sleep 10
            done
          fi

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
            /opt/homebrew
          key: ${{ runner.os }}-${{ runner.arch }}-homebrew-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-homebrew-

      - name: Install macOS Dependencies
        run: brew install ccache git git-lfs cmake python clang-format flex bison cppcheck
        shell: bash
      
      - name: Cache CMake Build for faster rebuilds
        uses: actions/cache@v4
        with:
          path: |
            build/
            ~/.ccache
          key: ${{ runner.os }}-${{ matrix.os_arch }}-cmake-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os_arch }}-cmake-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt') }}
            ${{ runner.os }}-${{ matrix.os_arch }}-cmake-

      - name: Setup Build Environment
        run: |
          echo "Setting up build environment for ${{ matrix.os_arch }}..."
          export SDKROOT=$(xcrun --show-sdk-path)
          export CFLAGS="-isysroot $SDKROOT"
          export CXXFLAGS="-isysroot $SDKROOT"
          
          echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
          echo "CFLAGS=-isysroot $SDKROOT" >> $GITHUB_ENV
          echo "CXXFLAGS=-isysroot $SDKROOT" >> $GITHUB_ENV
          
      - name: Configure CMake
        run: |
          echo "Creating build directory and configuring..."
          mkdir -p build && cd build
          
          cmake \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.CMAKE_OSX_DEPLOYMENT_TARGET }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_OSX_SYSROOT=$SDKROOT \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.cmake_arch }} \
            -DOSQUERY_VERSION="5.9.1" \
            ..
            
          echo "CMake configuration completed"

      - name: Build Project
        run: |
          echo "Starting build for ${{ matrix.os_arch }}..."
          cd build
          
          CPU_COUNT=$(sysctl -n hw.ncpu)
          echo "Building with $CPU_COUNT parallel jobs"
          time cmake --build . -j $CPU_COUNT
          
          echo "Build completed successfully"

      - name: Upload client artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/osquery/${{ env.BINARY_NAME }}
          if-no-files-found: warn
          retention-days: 30
          compression-level: 9

  create_universal_macos:
    name: "Create Universal macOS Binary"
    needs: [build_macos]
    runs-on: macos-latest
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      !failure() && !cancelled()
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download macOS x86-64 Binary
        uses: actions/download-artifact@v4
        with:
          name: osquery-macos-x64
          path: x64-artifacts/

      - name: Download macOS ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: osquery-macos-arm64
          path: arm64-artifacts/

      - name: Create Universal Binary
        run: |
          echo "Creating universal macOS binary..."
          X64_BINARY="x64-artifacts/${{ env.BINARY_NAME }}"
          ARM64_BINARY="arm64-artifacts/${{ env.BINARY_NAME }}"
          
          echo "Creating universal binary with lipo..."
          mkdir -p artifacts
          lipo -create "$X64_BINARY" "$ARM64_BINARY" -output ./artifacts/${{ env.BINARY_NAME }}
          
          # Verify universal binary
          echo "Universal binary info:"
          lipo -info ./artifacts/${{ env.BINARY_NAME }}
          file ./artifacts/${{ env.BINARY_NAME }}
          
      - name: Sign MacOS package
        uses: ./.github/steps/sign-macos-package
        with:
          apple_certificate_p12: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          apple_certificate_password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          apple_developer_id: ${{ secrets.APPLE_DEVELOPER_ID }}
          apple_id_username: ${{ secrets.APPLE_ID_USERNAME }}
          apple_id_password: ${{ secrets.APPLE_ID_PASSWORD }}
          apple_team_id: ${{ secrets.APPLE_TEAM_ID }}
          binary_name: ${{ env.BINARY_NAME }}

      - name: Upload Universal Binary
        uses: actions/upload-artifact@v4
        with:
          name: osquery-macos-universal
          path: artifacts/
          retention-days: 30
          compression-level: 9

  build_windows:
    name: "Build C Client for (${{ matrix.os }} ${{ matrix.os_arch }})"
    runs-on: ${{ matrix.os }}
    if: |
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows x64"
            os: windows-latest
            os_arch: x64
            artifact_name: osquery-windows-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup Visual Studio Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.os_arch }}      
      
      - name: Configure CMake for ${{ matrix.os }}
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A ${{ matrix.os_arch }} -DOSQUERY_VERSION="5.9.1" ..

      - name: Build OSQuery for Windows ${{ matrix.os_arch }} with MSBuild
        run: |
          cd build
          cmake --build . --config RelWithDebInfo -j10

      - name: Upload Windows OSQuery artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: "build/osquery/RelWithDebInfo/${{ env.BINARY_NAME }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}"
          if-no-files-found: warn
          retention-days: 30
          compression-level: 9
